package sampleApp.model;

import javax.validation.Valid;
import javax.validation.constraints.*;
import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.validation.annotation.Validated;

import java.util.Date;
import javax.persistence.*;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.Date;

@Entity
@Table(name = "registrations")
public class Registration {


    // An autogenerated id (unique for each user in the db)
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name="rowid")
    private int rowid;

    @NotEmpty(message = "Please enter your first name")
    private String firstName;

    @NotEmpty(message = "Please enter your last name")
    private String lastName;

    @NotEmpty(message = "Please enter your first address line")
    private String address1;

    private String address2;

    @NotEmpty(message = "Please enter your city")
    private String city;

    @NotEmpty(message = "Please select your state")
    private String state;

    @NotNull
    @Pattern(regexp="^[0-9]{5}(?:-[0-9]{4})?$", message = "Your ZIP code must either 5 or 9 digits")
    private String zip;

    @NotEmpty(message = "Please enter your country (US only)")
    private String country;

    private Timestamp regDate;

    public Registration() {
    }

    public Registration(int rowid, String firstName, String lastName, String address1,
                        String address2, String city, String state,
                        String zip, String country) {
        this.rowid = rowid;
        this.firstName = firstName;
        this.lastName = lastName;
        this.address1 = address1;
        this.address2 = address2;
        this.city = city;
        this.state = state;
        this.zip = zip;
        this.country = country;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getAddress1() {
        return address1;
    }

    public void setAddress1(String address1) {
        this.address1 = address1;
    }

    public String getAddress2() {
        return address2;
    }

    public void setAddress2(String address2) {
        this.address2 = address2;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getZip() {
        return zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    public String getCountry() {
        return country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    public Timestamp getRegDate() { return regDate; }

    public void setRegDate(Timestamp regDate) { this.regDate = regDate; }

    public int getRowid() {
        return rowid;
    }

    public void setRowid(int rowid) {
        this.rowid = rowid;
    }
}
